### ISSUE TITLE
Implement some kind of categories

### ISSUE THREAD

**Issue by bottomquark** [SimpleTimeTracking/StandaloneClient#12]
When creating a report, it should be possible to group the report items by some kind of category.

Ideas:
- automatically group by a common prefix of item comments
- use some kind of marker (like enclosing qoutes) to specify groups.
  Example: `stt on "main category""subcategory" the long comment`

Quotes may be not the best option because of escaping in shells. Maybe percent signs % or exclamation marks ! would be better.

Optionally, the marker should be configurable by the user

**Comment by Bytekeeper** [comment]
@bottomquark I can't find any purpose for the TreeView, do you?

**Comment by bottomquark** [comment]
not really. For me, copy & pasting entries is sufficient and I think that a TreeView could make that more complicated?
