### ISSUE TITLE
Provide undo and redo functionality

### ISSUE THREAD

**Issue by bottomquark** [SimpleTimeTracking/StandaloneClient#13]

**Comment by Bytekeeper** [comment]
I can't remember what this one was, can you?

**Comment by bottomquark** [comment]
I think that was intended to fix typos or remove an item if typing wrong stuff and hitting "save"? Maybe something like this could be useful with the CLI but I'm not sure how it could work...

**Comment by EricThieme** [comment]
I think also that the idea was to undo changes after you saved sth. by mistake that removed sth. else,

**Comment by Bytekeeper** [comment]
Ok. There is a log of executed changes and the UI warns if items are deleted or would overwritten. I did not required an undo since I added those validation dialogs. Closing this one.
