### ISSUE TITLE
And new command: resume last

### ISSUE THREAD

**Issue by Bytekeeper** [SimpleTimeTracking/StandaloneClient#43]
It should resume the last activity:
* Do nothing if the last activity is still active
* Create a new activity starting now with the same text as the last one

**Comment by bottomquark** [comment]
If possible, the name of the command should not start with "r" as the CLI uses "report" as a command and I use that about 10 times a day typing "stt r" which could conflict with "resume".

**Comment by Bytekeeper** [comment]
@bottomquark  The CLI part is missing.
