### ISSUE TITLE
Better delete logic

### ISSUE THREAD

**Issue by Bytekeeper** [SimpleTimeTracking/StandaloneClient#46]
If an item is deleted:
Use cases:

1. Delete item between equal activities

|--A--|--B--|--A--|
Delete B =>
|-------A----------|

2. Delete item between non-equal activities

|--A--|--B--|--C--|
Delete B =>
|--A--|       |--C--|

3. Delete item that is ongoing

|--A--|--B--
Delete B =>
|--A---------
(This is problematic if a user tries to end the day with "fin" and mistypes. If he deletes the "typo item", the old activity would continue)

**Comment by EricThieme** [comment]
3. would be really helpfull. Although I really got used to change A afterwards and replace from with since :D

**Comment by Bytekeeper** [comment]
Should work.
