### ISSUE TITLE
Fix gradle file, so it can be compiled on my Mac/windows

### ISSUE THREAD

**Issue by barclay-reg** [SimpleTimeTracking/StandaloneClient#63]
Some of the changes within https://github.com/SimpleTimeTracking/StandaloneClient/commit/e0e3f8ac58581bfbe64262f33477a5bc9c7a8df4 make troubles, especially the dependency:

`implementation(files("/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jfxrt.jar"))`

**Comment by Bytekeeper** [comment]
Yes, that was a quick hack local path thing. Oracle made a mess with moving jfxrt.jar around between different directories.
